name: perf-test-django-uwsgi

services:
  uwsgi:
    build:
      context: ../../
      dockerfile: ci/docker/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - uwsgi:/tmp/uwsgi
      - ../../app/src:/app
    environment:
      - DJANGO_SETTINGS_MODULE=app.settings
      - PYTHONUNBUFFERED=1
      - DSN__RABBITMQ=${DSN__RABBITMQ}
    networks:
      - perf-test-rmq

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - uwsgi:/tmp/uwsgi
    depends_on:
      - uwsgi
    networks:
      - perf-test-rmq

volumes:
  uwsgi:

networks:
  perf-test-rmq:
    external: true
    name: perf-test-rmq
