name: perf-test-rust-actix

services:
  rust_actix:
    build:
      context: ../../
      dockerfile: ci/docker/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - rust_actix:/tmp/rust_actix
    environment:
      - DSN__RABBITMQ=${DSN__RABBITMQ}
      - SOCKET_PATH=/tmp/rust_actix/app.sock
      - RUST_LOG=info
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - perf-test-rmq

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8090:80"
    volumes:
      - rust_actix:/tmp/rust_actix
    depends_on:
      - rust_actix
    networks:
      - perf-test-rmq

volumes:
  rust_actix:

networks:
  perf-test-rmq:
    external: true
    name: perf-test-rmq
