name: perf-test-rust-hyper

services:
  rust_hyper:
    build:
      context: ../../
      dockerfile: ci/docker/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - rust_hyper:/tmp/rust_hyper
    environment:
      - DSN__RABBITMQ=${DSN__RABBITMQ}
      - SOCKET_PATH=/tmp/rust_hyper/app.sock
      - RUST_LOG=info
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - perf-test-rmq

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8092:80"
    volumes:
      - rust_hyper:/tmp/rust_hyper
    depends_on:
      - rust_hyper
    networks:
      - perf-test-rmq

volumes:
  rust_hyper:

networks:
  perf-test-rmq:
    external: true
    name: perf-test-rmq
