name: perf-test-fastapi-uvicorn

services:
  uvicorn:
    build:
      context: ../../
      dockerfile: ci/docker/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - uvicorn:/tmp/uvicorn
      - ../../app/src:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DSN__RABBITMQ=${DSN__RABBITMQ}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - perf-test-rmq

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8085:80"
    volumes:
      - uvicorn:/tmp/uvicorn
    depends_on:
      - uvicorn
    networks:
      - perf-test-rmq

volumes:
  uvicorn:

networks:
  perf-test-rmq:
    external: true
    name: perf-test-rmq
