name: perf-test-golang

services:
  golang:
    build:
      context: ../../
      dockerfile: ci/docker/backend/Dockerfile
    restart: unless-stopped
    volumes:
      - golang_socket:/tmp/golang
    environment:
      - DSN__RABBITMQ=${DSN__RABBITMQ}
      - SOCKET_PATH=/tmp/golang/app.sock
    networks:
      - perf-test-rmq

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - golang_socket:/tmp/golang
    depends_on:
      - golang
    networks:
      - perf-test-rmq

volumes:
  golang_socket:

networks:
  perf-test-rmq:
    external: true
    name: perf-test-rmq
